### ISSUE TITLE
Maven Central

### ISSUE THREAD

**Issue by yegor256** [radai-rosenblatt/grep-maven-plugin#2] opened 2015-06-04 17:22 UTC
Would be very convenient to have this plugin in Maven Central. Maybe this article will help you: http://www.yegor256.com/2014/08/19/how-to-release-to-maven-central.html

**Comment by c-rack** [comment] 2015-06-06 18:09
+1

**Comment by radai-rosenblatt** [comment] 2015-06-06 19:02
im working on deploying this to the sonatype oss repository (https://oss.sonatype.org/) - cant get this into central as its a snapshot version (although could in theory stage from OSS ...).

should happen within 1-2 days

**Comment by radai-rosenblatt** [comment] 2015-06-06 19:14
scratch that, its already up on oss - https://oss.sonatype.org/#nexus-search;quick~net.radai.
you just need to add sonatype oss as a plugin repo ...

**Comment by radai-rosenblatt** [comment] 2015-06-12 06:34
so further comments to i assume this is good enough for now

**Comment by c-rack** [comment] 2015-06-12 06:46
@radai-rosenblatt I think the issue is not resolved yet, because it is not available in maven central:
https://search.maven.org/#search|ga|1|net.radai
https://search.maven.org/#search|ga|1|grep

I would vote to re-open this.

**Comment by radai-rosenblatt** [comment] 2015-06-12 06:55
its not on central simply because there's no stable version released yet. if/when 1.0 (or any non-snapshot) comes out it will be stages there from sonatype.

**Comment by c-rack** [comment] 2015-06-12 07:11
Agree, but in my understanding, an issue should be closed only when either resolved or won't fix. If current project state does not allow to resolve it immediately that should not be a reason to close.

Nevertheless, it is your project, so you decide.
Please take my comments just as a friendly recommendation.

**Comment by radai-rosenblatt** [comment] 2016-07-14 02:22
project has been deployed to central - https://repo1.maven.org/maven2/net/radai/

**Closed by radai-rosenblatt** 2016-07-14 02:22 UTC
